### ISSUE TITLE
How to make mods for xash 3d half life

### ISSUE THREAD

**Issue by abbes255** [FWGS/hlsdk-xash3d#148]
How to build a mods for half life xash3d plz

**Comment by nekonomicon** [comment]
https://github.com/FWGS/hlsdk-xash3d/blob/master/README.md

**Comment by abbes255** [comment]
I not understand 😭

**Comment by abbes255** [comment]
Ok i read it but i have a problem
Is error: [Error 2] no such file or directory '/Sdk/build_tools'

**Comment by a1batross** [comment]
Can you post whole log?

Wtf is `/Sdk`? Why won't you try just build your mod for Windows first?

**Comment by abbes255** [comment]
iyed@iyed-VirtualBox:~/xash3d-android-project$ sh compile.sh release
-- Configuring for Android SDK/NDK
package su.xash.engine;
public class XashConfig {
public static final boolean PKG_TEST = false;
public static final boolean CHECK_SIGNATURES = false;
public static final boolean RELEASE = false;
public static final boolean GP_VERSION = false;
}
<?xml version="1.0" encoding="utf-8"?>
<resources>
<string name="git_revisions"><b>Version information:</b>  android/\n<b>hlsdk-xash3d:</b> a7103c1c waf: upgrade to waifu 1.1.0 \n<b>xash3d-fwgs:</b> 586d613 ref_soft: uncomment texture API functions implementations, they must be working now \niyed@iyed-VirtualBox 11:31:19-05-03-21</string>
</resources>
Setting top to                           : /home/iyed/xash3d-android-project 
Setting out to                           : /home/iyed/xash3d-android-project/build 
Build type                               : release 
--> android                              : in progress 
Checking for program 'javac'             : /usr/bin/javac 
Checking for program 'java'              : /usr/bin/java 
Checking for program 'jar'               : /usr/bin/jar 
Checking for program 'javadoc'           : /usr/bin/javadoc 
Checking environment variables           : ok 
Traceback (most recent call last):
  File "/home/iyed/xash3d-android-project/.waf-2.0.18-ff338576c6abcf8ea755ffa7e678f790/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/iyed/xash3d-android-project/.waf-2.0.18-ff338576c6abcf8ea755ffa7e678f790/waflib/Scripting.py", line 182, in run_commands
    ctx=run_command(cmd_name)
  File "/home/iyed/xash3d-android-project/.waf-2.0.18-ff338576c6abcf8ea755ffa7e678f790/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/home/iyed/xash3d-android-project/.waf-2.0.18-ff338576c6abcf8ea755ffa7e678f790/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/home/iyed/xash3d-android-project/.waf-2.0.18-ff338576c6abcf8ea755ffa7e678f790/waflib/Context.py", line 91, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/iyed/xash3d-android-project/.waf-2.0.18-ff338576c6abcf8ea755ffa7e678f790/waflib/Context.py", line 132, in recurse
    user_function(self)
  File "/home/iyed/xash3d-android-project/wscript", line 86, in configure
    conf.recurse(i.name)
  File "/home/iyed/xash3d-android-project/.waf-2.0.18-ff338576c6abcf8ea755ffa7e678f790/waflib/Context.py", line 132, in recurse
    user_function(self)
  File "/home/iyed/xash3d-android-project/android/wscript", line 11, in configure
    conf.load('android')
  File "/home/iyed/xash3d-android-project/.waf-2.0.18-ff338576c6abcf8ea755ffa7e678f790/waflib/Configure.py", line 156, in load
    func(self)
  File "/home/iyed/xash3d-android-project/scripts/waifulib/android.py", line 52, in configure
    btv = get_latest_build_tools_version(sdk)
  File "/home/iyed/xash3d-android-project/scripts/waifulib/android.py", line 27, in get_latest_build_tools_version
    dirs = os.listdir(build_tools_path)
OSError: [Errno 2] No such file or directory: '/Sdk/build-tools'

**Comment by abbes255** [comment]
Can you help me

**Comment by abbes255** [comment]
And i install android Sdk and ndk

**Comment by a1batross** [comment]
At first, **LEARN MARKDOWN**. No one will read that unformatted mess. See: https://github.github.com/gfm/

At second, make your mod for normal PCs first, then ask how to build it for Android.
Also, you don't need to build `xash3d-android-project`, it's engine project and wasn't made for modding.

**Comment by abbes255** [comment]
Ok

**Comment by abbes255** [comment]
how to build it for Android now

**Comment by a1batross** [comment]
I don't know. ^^

**Comment by abbes255** [comment]
Bruh
